=== leximayfield/WADVault/sources/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "WADVault",
	"description": "Schema used by metadata files used by WADVault.",
	"type": "object",
	"required": [
		"uid",
		"files"
	],
	"properties": {
		"uid": {
			"description": "Unique identifier per entry",
			"type": "string"
		},
		"name": {
			"description": "Name of entry",
			"type": "string"
		},
		"description": {
			"description": "Detailed information about entry",
			"type": "string"
		},
		"files": {
			"description": "List of files in entry",
			"type": "array",
			"items": {
				"type": "object",
				"required": [
					"filename",
					"size",
					"crc",
					"md5",
					"sha1"
				],
				"properties": {
					"filename": {
						"description": "Name of file",
						"type": "string"
					},
					"date": {
						"description": "Date of file in YYYY-MM-DD HH:MM:SS format",
						"type": "string"
					},
					"size": {
						"description": "Size of file in bytes",
						"type": "integer"
					},
					"crc": {
						"description": "CRC32 of file",
						"type": [
							"string",
							"integer"
						]
					},
					"md5": {
						"description": "MD5 hash of file",
						"type": "string",
						"length": 32
					},
					"sha1": {
						"description": "SHA1 hash of file",
						"type": "string",
						"length": 40
					},
					"sha256": {
						"description": "SHA256 hash of file",
						"type": "string",
						"length": 64
					}
				}
			}
		},
		"version": {
			"description": "Textual description of version",
			"type": "string"
		},
		"date": {
			"description": "Date of archive in YYYY-MM-DD HH:MM:SS format",
			"type": "string"
		}
	}
}

=== leximayfield/WADVault/sources/WAD Archive/60/roks_ma1.wad.json
{
	"uid": "roks_ma1.wad",
	"name": "ROKS \"Reach Out and Kill Someone\"",
	"description": "NEW BREED MAP03 converted to ROKS format",
	"date": "2014-12-15 21:26:43",
	"files": [
		{
			"filename": "roks_ma1.wad",
			"size": 95793,
			"crc": 2741016821,
			"md5": "1fb9a35b8ca6a48084883af5ed95c35c",
			"sha1": "60087118674b286d810d2b24e05a3d64bf28bce2",
			"sha256": "14a62b8529cc3fb0ad997f7dcc89b4ede3ad401ed58a6c785a656ca83d2cf2e2"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/17/flipside.wad.json
{
	"uid": "flipside.wad",
	"name": "Flipside, a multi-level Doom II Deathmatch WAD",
	"date": "2014-01-07 21:46:17",
	"files": [
		{
			"filename": "flipside.wad",
			"size": 555831,
			"crc": 2054822770,
			"md5": "bdf4f94b9b60f2e5190edf0e266c2640",
			"sha1": "1795204c5ab485f61521c4891756dc8c91ccb49e",
			"sha256": "918190c3ae880ef4f41c44c78dc6edbf611dec245de309e29da921475ac21a64"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/8a/db-e2m1 (8a36aa).wad.json
{
	"uid": "db-e2m1 (8a36aa).wad",
	"version": "8a36aa",
	"date": "2014-01-04 11:56:02",
	"files": [
		{
			"filename": "db-e2m1.wad",
			"size": 67103,
			"crc": 2570041842,
			"md5": "6edb440def5f4324f99f2f18e56269bb",
			"sha1": "8a36aa4c1cc7ff0d74adcf9237efcd7da787fc53",
			"sha256": "2ae771cd3e48907c39c0f60625b99a93f9cc8efbf336489a0790439f7fad0b47"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/85/legend (8551fd).wad.json
{
	"uid": "legend (8551fd).wad",
	"name": "legend.zip",
	"description": "This is a combo wad containing levels one, two, and three.",
	"version": "8551fd",
	"date": "2015-12-07 12:44:59",
	"files": [
		{
			"filename": "legend.wad",
			"size": 217614,
			"crc": 781204189,
			"md5": "43a37e63136f2ffe9483cf2eac5e46ae",
			"sha1": "8551fda5277f2e101ccaeb110771731e2357e932",
			"sha256": "a78d5f2bc80ed3b0c3f3588093fe82b0f14ad6c64bc1828e3dba53c09f7b0d96"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/ba/train2 (ba600b).wad.json
{
	"uid": "train2 (ba600b).wad",
	"name": "Space Marine Training Facility V2.0",
	"description": "The leaders of the Federation anticipating the possibility of an assult by the Denziens of Hell have constructed a training facility. The facility has been stocked with all weapons and plenty of ammo to train a marine in the use of various firepower. The Federation has also simulated, to the best of their knowledge, various beasts. Little is known about the creatures, so there might be more formidable foes awaiting in the real attack. The facitlity was built on the premise that 4 marines could simulate battle with each other, because the limited knowledge of the beasts makes for them to be rather predictable opponents.",
	"version": "ba600b",
	"date": "2013-11-02 15:11:36",
	"files": [
		{
			"filename": "train2.wad",
			"size": 74767,
			"crc": 1763404116,
			"md5": "6d9c382c4e7cf1f8adc73aaaee63c921",
			"sha1": "ba600b2dd94c69ec426e07a979b038a3da88b7c5",
			"sha256": "8d0d35f7d2205b09e9901fc65e9c5c331865220c0713615ea864fab9139dc9f0"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/e9/wtc911.wad.json
{
	"uid": "wtc911.wad",
	"name": "Waste Treatment Center #911",
	"date": "2014-12-14 20:51:17",
	"files": [
		{
			"filename": "wtc911.wad",
			"size": 344158,
			"crc": 2964672417,
			"md5": "36fb141417388e2fee817d6d13f90854",
			"sha1": "e99d18b0967c2bf5f05eb050f731d0db99be0e10",
			"sha256": "2ef35d489298f7ddd85ee87f6dad1224078e292305ba75dda0aa7c6354117a18"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/a2/star (a2b09b).wad.json
{
	"uid": "star (a2b09b).wad",
	"name": "Star",
	"description": "For those die hards out there who like Plutonia and H2HMUD, but want more!",
	"version": "a2b09b",
	"date": "2015-01-14 22:59:02",
	"files": [
		{
			"filename": "star.wad",
			"size": 559645,
			"crc": 2684742595,
			"md5": "b3ac04d4fcc2f7a7f6abb8e48c6facf2",
			"sha1": "a2b09bda67a6abb6877402ae100f666c3a857e98",
			"sha256": "c459984c5fd6443e7d4c82fa7beabacb1c495e816a9ed774905a8d780d2739a7"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/29/hellboundcomplex (29d2e6).wad.json
{
	"uid": "hellboundcomplex (29d2e6).wad",
	"version": "29d2e6",
	"date": "2017-03-22 20:41:10",
	"files": [
		{
			"filename": "hellboundcomplex.wad",
			"size": 2574428,
			"crc": 3767387559,
			"md5": "7239873723599763814910425ded3466",
			"sha1": "29d2e6c1f55c72233e7f6c39b8252b2c8cd4bd1e",
			"sha256": "fe9b01c2b0a6fa9803afafecd0dc01454cd1a68ad3a24c648b4709d1d8635ec3"
		}
	]
}
