=== leximayfield/WADVault/sources/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "WADVault",
	"description": "Schema used by metadata files used by WADVault.",
	"type": "object",
	"required": [
		"uid",
		"files"
	],
	"properties": {
		"uid": {
			"description": "Unique identifier per entry",
			"type": "string"
		},
		"name": {
			"description": "Name of entry",
			"type": "string"
		},
		"description": {
			"description": "Detailed information about entry",
			"type": "string"
		},
		"files": {
			"description": "List of files in entry",
			"type": "array",
			"items": {
				"type": "object",
				"required": [
					"filename",
					"size",
					"crc",
					"md5",
					"sha1"
				],
				"properties": {
					"filename": {
						"description": "Name of file",
						"type": "string"
					},
					"date": {
						"description": "Date of file in YYYY-MM-DD HH:MM:SS format",
						"type": "string"
					},
					"size": {
						"description": "Size of file in bytes",
						"type": "integer"
					},
					"crc": {
						"description": "CRC32 of file",
						"type": [
							"string",
							"integer"
						]
					},
					"md5": {
						"description": "MD5 hash of file",
						"type": "string",
						"length": 32
					},
					"sha1": {
						"description": "SHA1 hash of file",
						"type": "string",
						"length": 40
					},
					"sha256": {
						"description": "SHA256 hash of file",
						"type": "string",
						"length": 64
					}
				}
			}
		},
		"version": {
			"description": "Textual description of version",
			"type": "string"
		},
		"date": {
			"description": "Date of archive in YYYY-MM-DD HH:MM:SS format",
			"type": "string"
		}
	}
}

=== leximayfield/WADVault/sources/WAD Archive/33/FleshWizard (333297).wad.json
{
	"uid": "FleshWizard (333297).wad",
	"version": "333297",
	"date": "2013-04-19 09:35:42",
	"files": [
		{
			"filename": "FleshWizard.wad",
			"size": 161508,
			"crc": 2741234990,
			"md5": "56947c60001d1799a1bb67620b992b00",
			"sha1": "33329761f48671bcf42014b9b6ca86b7c834d5f6",
			"sha256": "83c6d76389c4d662ccc25a8cac67a52677c2318b957f9022af81bfdebcf93fa7"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/01/undc.wad.json
{
	"uid": "undc.wad",
	"name": "Rise of the Undead Cardinals",
	"description": "You are Pastor Greg Herbert, you have recently been hearing a strange voice from the Church Basement. As you investigate, you discover a large portal. Daring to enter, you load up your pistol and go inside.",
	"date": "2014-12-29 15:56:43",
	"files": [
		{
			"filename": "undc.wad",
			"size": 2638038,
			"crc": 4000709144,
			"md5": "c89d7d7c9688e82323ca4df139853315",
			"sha1": "0136d8f90d99cf2c2e178136c8e4486d8733bdce",
			"sha256": "a30a9f563de170dbf5fb5cccf1f6148550c0ece691634bd7ded5834f54ea78ec"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/99/barndoom.wad.json
{
	"uid": "barndoom.wad",
	"name": "Barney DOOM!",
	"date": "2015-09-14 20:47:17",
	"files": [
		{
			"filename": "barndoom.wad",
			"size": 168372,
			"crc": 4048514356,
			"md5": "107b2b0473b2eaf523055f2bbbbea779",
			"sha1": "99eb6542a0a264608043fa82defadadaf073f891",
			"sha256": "6911926a7ba9ea4e3bb3cd5a967a458f71d5e39048e9b088c8468a2c00e95adf"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/20/SOPHIL.wad.json
{
	"uid": "SOPHIL.wad",
	"name": "The Shores of Phil",
	"description": "An episode 2 theme mapset in a somewhat classic",
	"date": "2014-12-14 21:06:19",
	"files": [
		{
			"filename": "SOPHIL.wad",
			"size": 745173,
			"crc": 612577381,
			"md5": "7d0abff0629d0b24442d60d9c99eb895",
			"sha1": "20437ceeb0bce4e54cb5bf971bba265885b2065b",
			"sha256": "7be99e32dd8602267717648b645d58b0101079b63fb70be7874f346e72ff0ade"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/8a/stoneman (8aa484).wad.json
{
	"uid": "stoneman (8aa484).wad",
	"name": "Stoneman's Joint",
	"description": "DEATHMATCH !!!! This is designed for deathmatch only . There are monsters in the wad but they are also placed with deathmatch in mind . It can be played single player but there would be no purpose other than for firing practice. I tried to make an evil cross between levels one and seven",
	"version": "8aa484",
	"date": "2014-01-07 22:25:35",
	"files": [
		{
			"filename": "stoneman.wad",
			"size": 132035,
			"crc": 352552905,
			"md5": "fba00f7860106e00bb6bde185eea56a0",
			"sha1": "8aa48464c88cf91a0f53fd38e96b7c20aefb402e",
			"sha256": "17317a5c707db69053a9feb05699dbbced26cb718ba4050f5e9cf340899db231"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/fd/fearless (fdcae3).wad.json
{
	"uid": "fearless (fdcae3).wad",
	"name": "Fearless",
	"description": "As you stumble through the rocky landscape of the Deimos moon you come across a dead body, something you've become quite used to, clutching a burnt and shredded piece of paper. You pry the sheet from his fingers and read it. You can only make out a little, but its more than enough. The paper describes a device that is used as one of the main warp generators that is bringing in all of this nastiness. This poor soul went to destroy it, but he failed. Well we can't have that now, can we? The paper gives vague directions to a rear entrance that would provide less resistance, and a map of the complex, but unfortunately the map part is especially burnt and shredded. Oh well! You're on your way. You know it may be your last fight, but you've known for a while that there was no escaping this place. You're already dead. You have no fear.",
	"version": "fdcae3",
	"date": "2013-11-02 15:48:06",
	"files": [
		{
			"filename": "fearless.wad",
			"size": 102119,
			"crc": 2395052292,
			"md5": "e447052745b83390fcf857a749922dd7",
			"sha1": "fdcae379bf0f9d52bad9793b6218866ad1240931",
			"sha256": "beb05209652b0467f4827cdf2bc07f5bff0ee2032705681592bc7e8995523cd0"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/a1/XCALIBR!.wad.json
{
	"uid": "XCALIBR!.wad",
	"name": "Excalibur 1.1",
	"date": "2014-08-30 13:50:04",
	"files": [
		{
			"filename": "XCALIBR!.wad",
			"size": 366738,
			"crc": 3462563172,
			"md5": "f3f2e0221a03a257788f01112ab88ce9",
			"sha1": "a18f87945c5ad38ae9ba5636943fdc266f3f0978",
			"sha256": "b83b7472dd8354f159c8a0bcfa47ce4fbe805b667c194c52e4f8a154804edcd7"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/b6/nuksewer.wad.json
{
	"uid": "nuksewer.wad",
	"name": "Nuke Sewer",
	"description": "Dark flickering sewer. Built from 10 sectors.",
	"date": "2015-01-13 21:22:00",
	"files": [
		{
			"filename": "nuksewer.wad",
			"size": 109054,
			"crc": 957315477,
			"md5": "4c8367772ed7aa78d33101814e0d38f2",
			"sha1": "b62a758ff911dc1252abca55609a30475eb1ce71",
			"sha256": "96cc182456f1b576a55d8ad21e728d9d544c6c292bb9788a857db2ba9beb3702"
		}
	]
}
