=== leximayfield/WADVault/sources/schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "WADVault",
	"description": "Schema used by metadata files used by WADVault.",
	"type": "object",
	"required": [
		"uid",
		"files"
	],
	"properties": {
		"uid": {
			"description": "Unique identifier per entry",
			"type": "string"
		},
		"name": {
			"description": "Name of entry",
			"type": "string"
		},
		"description": {
			"description": "Detailed information about entry",
			"type": "string"
		},
		"files": {
			"description": "List of files in entry",
			"type": "array",
			"items": {
				"type": "object",
				"required": [
					"filename",
					"size",
					"crc",
					"md5",
					"sha1"
				],
				"properties": {
					"filename": {
						"description": "Name of file",
						"type": "string"
					},
					"date": {
						"description": "Date of file in YYYY-MM-DD HH:MM:SS format",
						"type": "string"
					},
					"size": {
						"description": "Size of file in bytes",
						"type": "integer"
					},
					"crc": {
						"description": "CRC32 of file",
						"type": [
							"string",
							"integer"
						]
					},
					"md5": {
						"description": "MD5 hash of file",
						"type": "string",
						"length": 32
					},
					"sha1": {
						"description": "SHA1 hash of file",
						"type": "string",
						"length": 40
					},
					"sha256": {
						"description": "SHA256 hash of file",
						"type": "string",
						"length": 64
					}
				}
			}
		},
		"version": {
			"description": "Textual description of version",
			"type": "string"
		},
		"date": {
			"description": "Date of archive in YYYY-MM-DD HH:MM:SS format",
			"type": "string"
		}
	}
}

=== leximayfield/WADVault/sources/WAD Archive/73/bldscrpt.wad.json
{
	"uid": "bldscrpt.wad",
	"name": "The bloodstorm crypt",
	"description": "You've been trapped in the crypt for a week now ever since you were trapped off from the rest of your crew. You were dispatched here to contain a alleged demon infestation of a crypt. You've been trying to contact UAC, but to no avail. It looks like they've left you for dead... Will you crawl your way out alive? Or let the darkness consume you? This is truly the hardest test you'll ever go through in your life...",
	"date": "2017-08-27 23:00:37",
	"files": [
		{
			"filename": "bldscrpt.wad",
			"size": 432395,
			"crc": 3880774705,
			"md5": "a2da4b5f9d159b36030c0369d50423e3",
			"sha1": "733a54d79b458e0333d59fb5cb0ed0ff0dead6c6",
			"sha256": "dd4992f139c4e081daa8b27f9331dc3a853a7dbeeaf7f7bc8f596de14f5e1f61"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/d4/frigfrag (d453f6).wad.json
{
	"uid": "frigfrag (d453f6).wad",
	"name": "Frigid Frag",
	"description": "Winter is coming! This is a winter-themed deathmatch arena inspired by Brit10. Ideal for duels or 1-4 players.",
	"version": "d453f6",
	"date": "2015-02-07 14:21:02",
	"files": [
		{
			"filename": "frigfrag.wad",
			"size": 336574,
			"crc": 3451168189,
			"md5": "8dd0d4ffbd6f775b8d29c8b3e0ce9df4",
			"sha1": "d453f69e3354fe4494bee7f9c7198e49683f766b",
			"sha256": "4b34bd0ed516d9febf1f49a1ad3e9e130cb4791085fd91aa9e6be9e84c6c7176"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/68/rslquest-edthebat (68880d).wad.json
{
	"uid": "rslquest-edthebat (68880d).wad",
	"version": "68880d",
	"date": "2014-12-11 22:21:34",
	"files": [
		{
			"filename": "rslquest-edthebat.wad",
			"size": 13332851,
			"crc": 1384040635,
			"md5": "f2dd2930c91a234a155184c3c42c367a",
			"sha1": "68880da47f80896173d69e7c6a1d93b9472b957b",
			"sha256": "c37bf72e6ac5c3c321c9072b16485d9548beba3012e985e265a2c46034ef782b"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/ee/enigma (eef3e3).wad.json
{
	"uid": "enigma (eef3e3).wad",
	"name": "The Enigma",
	"version": "eef3e3",
	"date": "2013-11-02 16:01:51",
	"files": [
		{
			"filename": "enigma.wad",
			"size": 34681,
			"crc": 1280045295,
			"md5": "51aee2126b08b0cc6512f024f55a8c6d",
			"sha1": "eef3e3252df5923fa44ce4f29f03fc4e12c35d34",
			"sha256": "c18baa9b480e1f88770652bfb8da231325e2c873f92be9235373aa21543fe1e2"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/cc/linc95 (cce428).wad.json
{
	"uid": "linc95 (cce428).wad",
	"name": "Lincon95 tourney",
	"description": "This level was used in the doom2 tourney at the Lincon95 convent. It's a deathmatch only with all weapons but the hideous BFG ( the plasma dosn't have to much ammo either ). And there is no exit, so if you wich to se who fragged who most times, we recomend a time limit. One last thing, the arrows points at elevators just push the walls and they go down.",
	"version": "cce428",
	"date": "2014-01-07 22:16:13",
	"files": [
		{
			"filename": "linc95.wad",
			"size": 126632,
			"crc": 4288475675,
			"md5": "908f915df853bef96187244ec6bda2a6",
			"sha1": "cce42811b5e818830e8f2866bf58035922f213a4",
			"sha256": "577d05b415e0f23d3344026e69bba2b018e2b1c744c3ceb4a8d2c33fd6f6e599"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/30/kot-core-ce-eclipseupdate-beta-v1.7 (30a71e).pk3.json
{
	"uid": "kot-core-ce-eclipseupdate-beta-v1.7 (30a71e).pk3",
	"version": "30a71e",
	"date": "2021-01-10 03:19:13",
	"files": [
		{
			"filename": "kot-core-ce-eclipseupdate-beta-v1.7.pk3",
			"size": 25196175,
			"crc": 3217448204,
			"md5": "d159552d10c28464f3a995764c1c1163",
			"sha1": "30a71e7ab8aa6b299c8eae22e72994a3dd5c1ab0",
			"sha256": "b823a51e8d335c7b449c08cff60874f0c3f5df7ce34a4bf0a1347b551197ec24"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/02/MAP23 (02d555).wad.json
{
	"uid": "MAP23 (02d555).wad",
	"version": "02d555",
	"date": "2015-06-29 12:27:07",
	"files": [
		{
			"filename": "MAP23.wad",
			"size": 631146,
			"crc": 2808215546,
			"md5": "ddc1c5653b116f542a0758be42366694",
			"sha1": "02d55529b8661a49beb22deda56288711162c608",
			"sha256": "f7f11d87fd80a48e358cc72fda8ad3259c7c8728bcf9738abff343dbc4ee86d6"
		}
	]
}

=== leximayfield/WADVault/sources/WAD Archive/79/apoclps2 (79fc9b).wad.json
{
	"uid": "apoclps2 (79fc9b).wad",
	"name": "APOCALYPSE",
	"description": "This is a DOOM2 remake of my DOOM single player level, APOCLPSE. New creatures were added, old DOOM textures replaced, a few new secrets, and the SSG. Note: this WAD is much harder than the DOOM version was. Good Luck.",
	"version": "79fc9b",
	"date": "2016-02-07 20:31:22",
	"files": [
		{
			"filename": "apoclps2.wad",
			"size": 197129,
			"crc": 1627988038,
			"md5": "26b0972ab30ac4750cb6a6ba47287f20",
			"sha1": "79fc9b50f6d429092272c805e8cc3f0420c03817",
			"sha256": "60a3676068980f4e1054851a1313768f735b359a7f69c165d184c642525016dd"
		}
	]
}
